version: '3.8'

services:
  app:
    build: .
    container_name: uci_node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      # - DATABASE_URL=mongodb://mongo:27017/uci-proyecto-node
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: uci_node_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
